######################################################################
# Automatically generated by qmake (3.0) ?? ???. 9 12:33:31 2019
######################################################################

TEMPLATE = app
TARGET = "Пример для ручной сборки"
INCLUDEPATH += .
QT += gui widgets

# Input
SOURCES += main.cpp
